# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(397, 300)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        LoginDialog.setFont(font)
        LoginDialog.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.label = QtWidgets.QLabel(LoginDialog)
        self.label.setGeometry(QtCore.QRect(100, 70, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label.setObjectName("label")
        self.usernamelineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.usernamelineEdit.setGeometry(QtCore.QRect(170, 70, 113, 21))
        self.usernamelineEdit.setObjectName("usernamelineEdit")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setGeometry(QtCore.QRect(100, 130, 61, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_2.setObjectName("label_2")
        self.passwordlineEdit = QtWidgets.QLineEdit(LoginDialog)
        self.passwordlineEdit.setGeometry(QtCore.QRect(170, 130, 113, 21))
        self.passwordlineEdit.setObjectName("passwordlineEdit")
        self.loginpushButton = QtWidgets.QPushButton(LoginDialog)
        self.loginpushButton.setGeometry(QtCore.QRect(70, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.loginpushButton.setFont(font)
        self.loginpushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 170, 255);")
        self.loginpushButton.setObjectName("loginpushButton")
        self.registerpushButton = QtWidgets.QPushButton(LoginDialog)
        self.registerpushButton.setGeometry(QtCore.QRect(230, 200, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.registerpushButton.setFont(font)
        self.registerpushButton.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 170, 255);")
        self.registerpushButton.setObjectName("registerpushButton")

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "登录界面"))
        self.label.setText(_translate("LoginDialog", "帐号："))
        self.label_2.setText(_translate("LoginDialog", "密码："))
        self.loginpushButton.setText(_translate("LoginDialog", "登录"))
        self.registerpushButton.setText(_translate("LoginDialog", "注册"))
